name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "production"
jobs:
  deploy:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
      with:
        path: storybook-static
